"""SQLAlchemy models: the durable shape of a research run.

These mirror the Pydantic domain models rather than replacing them. The
separation is deliberate. Pydantic models are the contract between agents and
are validated on every construction; these are the storage representation, and
they carry things the domain models do not need -- foreign keys, indexes, and
cascade rules.

Keeping them apart means a schema change does not force an agent change, and an
agent's validation rules do not leak into the database.

Two conventions run through the schema:

*Ids are strings, generated by the application.* A research run creates a source
id before anything is written, references it in evidence, and may never persist
at all (a dry run, a failed run). Database-generated integers would force a
write to learn an id, which puts persistence in the middle of the research loop.

*Deleting a research session deletes everything it produced.* Its tasks,
sources, evidence, and runs have no meaning without it, and orphaned rows are
how a "sources" table quietly becomes unqueryable.
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _now() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    """Base for every model.

    ``type_annotation_map`` keeps column types out of individual definitions, so
    a Decimal is stored with the same precision everywhere rather than depending
    on which model was written first.
    """

    type_annotation_map = {  # noqa: RUF012
        datetime: DateTime(timezone=True),
        Decimal: Numeric(12, 8),
        dict[str, Any]: JSON,
    }


class User(Base):
    """An account, and the owner of everything it researches.

    The table existed from the first migration with nothing in it but an email,
    because ``research_sessions.user_id`` needed something to point at. What
    arrives here now is the part that makes the pointer mean something: a
    credential to prove you are the row, and a switch to stop you being it.
    """

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True)
    """Stored already lowercased and stripped.

    Normalising on write rather than on read is what makes the unique index a
    real constraint: ``Ada@example.com`` and ``ada@example.com`` are the same
    account to every mail server on earth, and a case-sensitive index would
    happily hold both and let one person register twice."""

    password_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)
    """Argon2id, parameters encoded in the string itself.

    Nullable because not every account has a password: an account created by
    the CLI so a local run has an owner never logs in, and a future identity
    provider would not bring one either. A NULL here means "cannot sign in with
    a password", which the login path treats as a failed verification rather
    than as a missing check."""

    display_name: Mapped[str | None] = mapped_column(String(120), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    """Whether this account may authenticate.

    A flag rather than a delete. Deleting a user cascades to every run they
    ever made, so "stop this person signing in" and "destroy their research"
    have to be separate actions -- otherwise the mild response to a suspected
    compromise is the destructive one."""

    created_at: Mapped[datetime] = mapped_column(default=_now)
    last_login_at: Mapped[datetime | None] = mapped_column(nullable=True)

    sessions: Mapped[list[ResearchSession]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class ResearchSession(Base):
    """One research run, from question to report."""

    __tablename__ = "research_sessions"
    __table_args__ = (
        # The history view: a user's runs, newest first. Without this it is a
        # sequential scan that grows with every run in the system.
        Index("ix_sessions_user_created", "user_id", "created_at"),
    )

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[str | None] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True
    )
    question: Mapped[str] = mapped_column(Text)
    normalized_question: Mapped[str | None] = mapped_column(Text, nullable=True)
    research_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    depth: Mapped[str] = mapped_column(String(16), default="standard")
    status: Mapped[str] = mapped_column(String(24), default="queued", index=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)

    spec: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    """The full QuerySpec as produced. Stored whole because reproducing a run
    means knowing exactly what it was interpreted as, not a subset of it."""

    plan: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    analysis: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    report: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    """The finished report, including its citation table.

    Stored beside the run rather than regenerated on read: it is the output of a
    paid model call, and a report that changed each time it was viewed would
    make the citation numbers in someone's notes point somewhere else."""

    report_markdown: Mapped[str | None] = mapped_column(Text, nullable=True)
    """The rendered document.

    Denormalised deliberately. Rendering is deterministic, so this is derivable
    -- but it is what an API returns and a reader downloads, and deriving it on
    every read means the display format is pinned to whatever the code does
    today rather than to what the reader was shown."""
    """What the evidence was found to support, with what grounding discarded.

    Stored whole, alongside the spec and the plan, rather than exploded into
    tables of findings and citations. Claims and their verification get real
    tables in the milestone that verifies them; until something queries a
    finding on its own, a column that keeps the analysis intact is the honest
    shape -- and a schema that promises query-ability nothing uses is worse than
    one that does not."""

    created_at: Mapped[datetime] = mapped_column(default=_now, index=True)
    started_at: Mapped[datetime | None] = mapped_column(nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)

    user: Mapped[User | None] = relationship(back_populates="sessions")
    tasks: Mapped[list[ResearchTaskRow]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )
    sources: Mapped[list[SourceRow]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )
    evidence: Mapped[list[EvidenceRow]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )
    claims: Mapped[list[ClaimRow]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )
    agent_runs: Mapped[list[AgentRunRow]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )
    tool_calls: Mapped[list[ToolCallRow]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )


class ResearchTaskRow(Base):
    __tablename__ = "research_tasks"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    research_id: Mapped[str] = mapped_column(
        ForeignKey("research_sessions.id", ondelete="CASCADE"), index=True
    )
    task_key: Mapped[str] = mapped_column(String(64))
    """The plan's slug. Distinct from the row id: the same task key can appear
    in a re-run, and the trace needs both which run and which task."""

    question: Mapped[str] = mapped_column(Text)
    priority: Mapped[str] = mapped_column(String(16), default="medium")
    parallelizable: Mapped[bool] = mapped_column(Boolean, default=True)
    dependencies: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
    status: Mapped[str] = mapped_column(String(24), default="pending", index=True)
    verdict: Mapped[str | None] = mapped_column(String(24), nullable=True)
    stop_reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    rounds: Mapped[int] = mapped_column(Integer, default=0)

    started_at: Mapped[datetime | None] = mapped_column(nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)

    session: Mapped[ResearchSession] = relationship(back_populates="tasks")


class SourceRow(Base):
    __tablename__ = "sources"
    __table_args__ = (
        # Deduplication asks "have we already fetched this URL in this run?" on
        # every search result, so it must not be a scan.
        Index("ix_sources_research_url", "research_id", "canonical_url"),
    )

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    research_id: Mapped[str] = mapped_column(
        ForeignKey("research_sessions.id", ondelete="CASCADE"), index=True
    )
    task_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    url: Mapped[str] = mapped_column(Text)
    canonical_url: Mapped[str] = mapped_column(Text)
    title: Mapped[str] = mapped_column(Text, default="")
    domain: Mapped[str] = mapped_column(String(253), default="", index=True)
    source_type: Mapped[str] = mapped_column(String(32), default="unknown", index=True)
    quality_score: Mapped[float] = mapped_column(Float, default=0.5)

    content: Mapped[str] = mapped_column(Text, default="")
    word_count: Mapped[int] = mapped_column(Integer, default=0)
    search_query: Mapped[str | None] = mapped_column(Text, nullable=True)
    fetch_failed: Mapped[bool] = mapped_column(Boolean, default=False)
    fetch_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    published_at: Mapped[datetime | None] = mapped_column(nullable=True)
    retrieved_at: Mapped[datetime] = mapped_column(default=_now)

    session: Mapped[ResearchSession] = relationship(back_populates="sources")
    evidence: Mapped[list[EvidenceRow]] = relationship(
        back_populates="source", cascade="all, delete-orphan"
    )


class EvidenceRow(Base):
    """A passage supporting a statement.

    ``source_id`` is a real foreign key, not a loose reference. Evidence whose
    source has been deleted cannot be traced back to anything, and untraceable
    evidence is exactly what this system exists to prevent -- so the database
    refuses to hold it.
    """

    __tablename__ = "evidence"
    __table_args__ = (Index("ix_evidence_research_source", "research_id", "source_id"),)

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    research_id: Mapped[str] = mapped_column(
        ForeignKey("research_sessions.id", ondelete="CASCADE"), index=True
    )
    source_id: Mapped[str] = mapped_column(ForeignKey("sources.id", ondelete="CASCADE"), index=True)
    task_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    claim: Mapped[str] = mapped_column(Text)
    supporting_text: Mapped[str] = mapped_column(Text)
    location: Mapped[str] = mapped_column(Text, default="")
    support_strength: Mapped[str] = mapped_column(String(16), default="moderate")

    quote_status: Mapped[str] = mapped_column(String(16), default="verbatim", index=True)
    quote_similarity: Mapped[float] = mapped_column(Float, default=1.0)
    source_quality: Mapped[float] = mapped_column(Float, default=0.5)
    weight: Mapped[float] = mapped_column(Float, default=0.5, index=True)
    """Stored rather than recomputed on read. It is derived, but the fact
    checker sorts by it across a whole run, and a computed sort cannot use an
    index."""

    extracted_at: Mapped[datetime] = mapped_column(default=_now)

    session: Mapped[ResearchSession] = relationship(back_populates="evidence")
    source: Mapped[SourceRow] = relationship(back_populates="evidence")


class ClaimRow(Base):
    """One assertion a run is prepared to make.

    Separate from evidence because it is a different kind of thing: evidence is
    quoted from a page, a claim is asserted by the system. Keeping them apart is
    what lets a claim be rejected without touching the evidence that suggested
    it, and lets a piece of evidence outlive a claim that turned out to be an
    overreach.
    """

    __tablename__ = "claims"
    __table_args__ = (
        # The report's query: the publishable claims of one run, strongest
        # first. Status leads because the report filters on it before ordering.
        Index("ix_claims_research_status", "research_id", "status"),
    )

    id: Mapped[str] = mapped_column(String(128), primary_key=True)
    research_id: Mapped[str] = mapped_column(
        ForeignKey("research_sessions.id", ondelete="CASCADE"), index=True
    )

    text: Mapped[str] = mapped_column(Text)
    kind: Mapped[str] = mapped_column(String(24), default="finding", index=True)
    status: Mapped[str] = mapped_column(String(24), default="proposed", index=True)
    confidence: Mapped[str] = mapped_column(String(16), default="moderate")

    condition: Mapped[str | None] = mapped_column(Text, nullable=True)
    merged_from: Mapped[int] = mapped_column(Integer, default=1)
    strength: Mapped[float] = mapped_column(Float, default=0.0, index=True)
    """Stored rather than recomputed, for the same reason evidence weight is: a
    report orders by it across a whole run and a computed sort cannot use an
    index."""

    disposition: Mapped[str | None] = mapped_column(String(24), nullable=True)
    verification_reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)
    overgeneralization: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggested_revision: Mapped[str | None] = mapped_column(Text, nullable=True)
    follow_up_question: Mapped[str | None] = mapped_column(Text, nullable=True)
    """What verification concluded, kept beside the claim it judged.

    On the claim rather than in a table of its own: there is exactly one verdict
    per claim, and a one-to-one table is a join that buys nothing. The
    contradicting passages it found are edges, and those do have a table."""

    contradicted_by: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    """Evidence ids that undercut this claim.

    The most valuable output of verification: a passage from another task that
    disagrees with a claim, which nothing before this stage brought into contact
    with it."""

    conflicts_with: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    """Ids of the claims this one contradicts.

    JSON rather than a self-referencing join table. A conflict is a small,
    symmetric annotation on a pair the analyst already identified, and it is
    never queried from the other direction -- a table for it would be schema
    that nothing reads."""

    created_at: Mapped[datetime] = mapped_column(default=_now)

    session: Mapped[ResearchSession] = relationship(back_populates="claims")
    evidence_links: Mapped[list[ClaimEvidenceRow]] = relationship(
        back_populates="claim", cascade="all, delete-orphan"
    )


class ClaimEvidenceRow(Base):
    """The edge between a claim and a passage supporting it.

    A join table rather than a column, because the relation is many to many in
    both directions and both directions get walked: verification asks what
    supports a claim, and a retracted source has to be traceable to everything
    built on top of it. A list of ids on the claim would answer only the first.
    """

    __tablename__ = "claim_evidence"
    __table_args__ = (
        PrimaryKeyConstraint("claim_id", "evidence_id"),
        # The reverse walk: everything resting on one passage.
        Index("ix_claim_evidence_evidence", "evidence_id"),
    )

    claim_id: Mapped[str] = mapped_column(ForeignKey("claims.id", ondelete="CASCADE"))
    evidence_id: Mapped[str] = mapped_column(ForeignKey("evidence.id", ondelete="CASCADE"))
    source_id: Mapped[str] = mapped_column(String(64), index=True)

    weight: Mapped[float] = mapped_column(Float, default=0.0)
    verbatim: Mapped[bool] = mapped_column(Boolean, default=False)
    """Whether the passage was found word for word in its source. Denormalised
    onto the edge so a verifier can weigh a claim's support without loading
    every passage behind it."""

    claim: Mapped[ClaimRow] = relationship(back_populates="evidence_links")


class AgentRunRow(Base):
    """One model call. The Postgres form of the JSONL run recorder."""

    __tablename__ = "agent_runs"
    __table_args__ = (Index("ix_agent_runs_research_started", "research_id", "started_at"),)

    run_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    research_id: Mapped[str | None] = mapped_column(
        ForeignKey("research_sessions.id", ondelete="CASCADE"), nullable=True, index=True
    )
    task_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    parent_run_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    agent: Mapped[str] = mapped_column(String(64), index=True)
    node: Mapped[str | None] = mapped_column(String(64), nullable=True)
    provider: Mapped[str] = mapped_column(String(32))
    model: Mapped[str] = mapped_column(String(96), index=True)
    tier: Mapped[str | None] = mapped_column(String(16), nullable=True)
    prompt_name: Mapped[str] = mapped_column(String(64), index=True)
    prompt_version: Mapped[str] = mapped_column(String(16))

    input_tokens: Mapped[int] = mapped_column(Integer, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, default=0)
    cached_tokens: Mapped[int] = mapped_column(Integer, default=0)
    latency_ms: Mapped[float] = mapped_column(Float, default=0.0)
    cost_usd: Mapped[Decimal | None] = mapped_column(Numeric(12, 8), nullable=True)
    """Nullable on purpose. A model with no recorded price stores NULL, not
    zero: SUM() then reports NULL rather than a total that looks free but is
    merely unmeasured."""

    status: Mapped[str] = mapped_column(String(16), default="success", index=True)
    error_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, default=0)
    finish_reason: Mapped[str | None] = mapped_column(String(32), nullable=True)

    started_at: Mapped[datetime] = mapped_column(default=_now)
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)

    session: Mapped[ResearchSession | None] = relationship(back_populates="agent_runs")


class ToolCallRow(Base):
    """One tool invocation, successful or not."""

    __tablename__ = "tool_calls"
    __table_args__ = (Index("ix_tool_calls_research_started", "research_id", "started_at"),)

    call_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    research_id: Mapped[str | None] = mapped_column(
        ForeignKey("research_sessions.id", ondelete="CASCADE"), nullable=True, index=True
    )
    task_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    parent_run_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

    tool: Mapped[str] = mapped_column(String(64), index=True)
    agent: Mapped[str | None] = mapped_column(String(64), nullable=True)
    arguments: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    latency_ms: Mapped[float] = mapped_column(Float, default=0.0)
    status: Mapped[str] = mapped_column(String(16), default="success", index=True)
    error_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, default=0)
    result_count: Mapped[int | None] = mapped_column(Integer, nullable=True)
    result_bytes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cache_hit: Mapped[bool] = mapped_column(Boolean, default=False)

    started_at: Mapped[datetime] = mapped_column(default=_now)
    completed_at: Mapped[datetime | None] = mapped_column(nullable=True)

    session: Mapped[ResearchSession | None] = relationship(back_populates="tool_calls")
