"""record verification on claims

Revision ID: 5dda85d1ba83
Revises: a91da564cb0f
Create Date: 2026-08-22 23:29:46.866647

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5dda85d1ba83"
down_revision: Union[str, Sequence[str], None] = "a91da564cb0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claims", sa.Column("disposition", sa.String(length=24), nullable=True))
    op.add_column("claims", sa.Column("verification_reasoning", sa.Text(), nullable=True))
    op.add_column("claims", sa.Column("overgeneralization", sa.Text(), nullable=True))
    op.add_column("claims", sa.Column("suggested_revision", sa.Text(), nullable=True))
    op.add_column("claims", sa.Column("follow_up_question", sa.Text(), nullable=True))
    op.add_column("claims", sa.Column("contradicted_by", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("claims", "contradicted_by")
    op.drop_column("claims", "follow_up_question")
    op.drop_column("claims", "suggested_revision")
    op.drop_column("claims", "overgeneralization")
    op.drop_column("claims", "verification_reasoning")
    op.drop_column("claims", "disposition")
    # ### end Alembic commands ###
