"""add analysis to research sessions

Revision ID: 7bb03fa1c99d
Revises: b118eb2defd3
Create Date: 2026-08-22 23:12:18.656953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bb03fa1c99d"
down_revision: Union[str, Sequence[str], None] = "b118eb2defd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("research_sessions", sa.Column("analysis", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_sessions", "analysis")
    # ### end Alembic commands ###
