"""store the report on the session

Revision ID: a0c84dc96310
Revises: 5dda85d1ba83
Create Date: 2026-08-22 23:57:21.674732

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0c84dc96310"
down_revision: Union[str, Sequence[str], None] = "5dda85d1ba83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("research_sessions", sa.Column("report", sa.JSON(), nullable=True))
    op.add_column("research_sessions", sa.Column("report_markdown", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_sessions", "report_markdown")
    op.drop_column("research_sessions", "report")
    # ### end Alembic commands ###
