"""add claims and claim evidence links

Revision ID: a91da564cb0f
Revises: 7bb03fa1c99d
Create Date: 2026-08-22 23:20:35.913839

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a91da564cb0f"
down_revision: Union[str, Sequence[str], None] = "7bb03fa1c99d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("research_id", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("merged_from", sa.Integer(), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("conflicts_with", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["research_id"], ["research_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_claims_kind"), "claims", ["kind"], unique=False)
    op.create_index(op.f("ix_claims_research_id"), "claims", ["research_id"], unique=False)
    op.create_index("ix_claims_research_status", "claims", ["research_id", "status"], unique=False)
    op.create_index(op.f("ix_claims_status"), "claims", ["status"], unique=False)
    op.create_index(op.f("ix_claims_strength"), "claims", ["strength"], unique=False)
    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("verbatim", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["claims.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id", "evidence_id"),
    )
    op.create_index("ix_claim_evidence_evidence", "claim_evidence", ["evidence_id"], unique=False)
    op.create_index(
        op.f("ix_claim_evidence_source_id"), "claim_evidence", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_claim_evidence_source_id"), table_name="claim_evidence")
    op.drop_index("ix_claim_evidence_evidence", table_name="claim_evidence")
    op.drop_table("claim_evidence")
    op.drop_index(op.f("ix_claims_strength"), table_name="claims")
    op.drop_index(op.f("ix_claims_status"), table_name="claims")
    op.drop_index("ix_claims_research_status", table_name="claims")
    op.drop_index(op.f("ix_claims_research_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_kind"), table_name="claims")
    op.drop_table("claims")
    # ### end Alembic commands ###
