"""create research schema

Revision ID: b118eb2defd3
Revises:
Create Date: 2026-08-21 16:31:47.072626

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b118eb2defd3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "research_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=True),
        sa.Column("research_type", sa.String(length=32), nullable=True),
        sa.Column("depth", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("spec", sa.JSON(), nullable=True),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_sessions_created_at"), "research_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_research_sessions_status"), "research_sessions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_research_sessions_user_id"), "research_sessions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_sessions_user_created", "research_sessions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "agent_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("research_id", sa.String(length=64), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("parent_run_id", sa.String(length=64), nullable=True),
        sa.Column("agent", sa.String(length=64), nullable=False),
        sa.Column("node", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=96), nullable=False),
        sa.Column("tier", sa.String(length=16), nullable=True),
        sa.Column("prompt_name", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["research_id"], ["research_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_agent_runs_agent"), "agent_runs", ["agent"], unique=False)
    op.create_index(op.f("ix_agent_runs_model"), "agent_runs", ["model"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_parent_run_id"), "agent_runs", ["parent_run_id"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_prompt_name"), "agent_runs", ["prompt_name"], unique=False)
    op.create_index(op.f("ix_agent_runs_research_id"), "agent_runs", ["research_id"], unique=False)
    op.create_index(
        "ix_agent_runs_research_started", "agent_runs", ["research_id", "started_at"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_status"), "agent_runs", ["status"], unique=False)
    op.create_table(
        "research_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("research_id", sa.String(length=64), nullable=False),
        sa.Column("task_key", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("parallelizable", sa.Boolean(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=True),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["research_id"], ["research_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_tasks_research_id"), "research_tasks", ["research_id"], unique=False
    )
    op.create_index(op.f("ix_research_tasks_status"), "research_tasks", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("research_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("search_query", sa.Text(), nullable=True),
        sa.Column("fetch_failed", sa.Boolean(), nullable=False),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["research_id"], ["research_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_domain"), "sources", ["domain"], unique=False)
    op.create_index(op.f("ix_sources_research_id"), "sources", ["research_id"], unique=False)
    op.create_index(
        "ix_sources_research_url", "sources", ["research_id", "canonical_url"], unique=False
    )
    op.create_index(op.f("ix_sources_source_type"), "sources", ["source_type"], unique=False)
    op.create_index(op.f("ix_sources_task_id"), "sources", ["task_id"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("research_id", sa.String(length=64), nullable=True),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("parent_run_id", sa.String(length=64), nullable=True),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("agent", sa.String(length=64), nullable=True),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("result_bytes", sa.Integer(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["research_id"], ["research_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(op.f("ix_tool_calls_research_id"), "tool_calls", ["research_id"], unique=False)
    op.create_index(
        "ix_tool_calls_research_started", "tool_calls", ["research_id", "started_at"], unique=False
    )
    op.create_index(op.f("ix_tool_calls_status"), "tool_calls", ["status"], unique=False)
    op.create_index(op.f("ix_tool_calls_tool"), "tool_calls", ["tool"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("research_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("supporting_text", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("support_strength", sa.String(length=16), nullable=False),
        sa.Column("quote_status", sa.String(length=16), nullable=False),
        sa.Column("quote_similarity", sa.Float(), nullable=False),
        sa.Column("source_quality", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["research_id"], ["research_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_quote_status"), "evidence", ["quote_status"], unique=False)
    op.create_index(op.f("ix_evidence_research_id"), "evidence", ["research_id"], unique=False)
    op.create_index(
        "ix_evidence_research_source", "evidence", ["research_id", "source_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_source_id"), "evidence", ["source_id"], unique=False)
    op.create_index(op.f("ix_evidence_weight"), "evidence", ["weight"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_weight"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_source_id"), table_name="evidence")
    op.drop_index("ix_evidence_research_source", table_name="evidence")
    op.drop_index(op.f("ix_evidence_research_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_quote_status"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_tool_calls_tool"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_status"), table_name="tool_calls")
    op.drop_index("ix_tool_calls_research_started", table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_research_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_sources_task_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_source_type"), table_name="sources")
    op.drop_index("ix_sources_research_url", table_name="sources")
    op.drop_index(op.f("ix_sources_research_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_domain"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_research_tasks_status"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_research_id"), table_name="research_tasks")
    op.drop_table("research_tasks")
    op.drop_index(op.f("ix_agent_runs_status"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_research_started", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_research_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_prompt_name"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_parent_run_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_model"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_sessions_user_created", table_name="research_sessions")
    op.drop_index(op.f("ix_research_sessions_user_id"), table_name="research_sessions")
    op.drop_index(op.f("ix_research_sessions_status"), table_name="research_sessions")
    op.drop_index(op.f("ix_research_sessions_created_at"), table_name="research_sessions")
    op.drop_table("research_sessions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
