"""give users credentials

Revision ID: c4e17a2b90d3
Revises: a0c84dc96310
Create Date: 2026-08-23 00:00:00.000000

Written by hand rather than autogenerated. The last time a migration was
autogenerated against this database it silently included four ``drop_table``
calls for LangGraph's checkpoint tables, which Alembic does not manage and
therefore believed were unwanted -- applying it would have deleted every
checkpoint in the system. A four-column change is not worth running that risk
again.

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4e17a2b90d3"
down_revision: Union[str, Sequence[str], None] = "a0c84dc96310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Give the users table the columns an account needs to sign in."""
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("display_name", sa.String(length=120), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))

    # NOT NULL on a table that may already have rows needs a value for them, so
    # the column arrives with a server default, and the default is then dropped.
    # Leaving it in place would mean the database and the model disagree about
    # where the default lives, and every future autogenerate would propose
    # "fixing" it in one direction or the other.
    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column("users", "is_active", server_default=None)


def downgrade() -> None:
    """Take them away again.

    This drops password hashes, which is not recoverable -- every account has to
    set a password again after a downgrade and re-upgrade. Said plainly here
    because a downgrade that loses credentials should be a decision, not a
    surprise.
    """
    op.drop_column("users", "is_active")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "display_name")
    op.drop_column("users", "password_hash")
